language: c
sudo: false

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -n test python=$python numpy scipy scikit-learn openmm mdtraj openmmtools -c omnia -c conda-forge
  - source activate test
  - conda list
  - pip install pydiffmap

before_script:
  - python -V

script:
  - python main_run.py --iterations 2 --replicas 2 --nrsteps 1000 --folderName 'test_travis' --algorithm 0
  - python main_run.py --iterations 2 --replicas 2 --nrsteps 1000 --folderName 'test_travis' --algorithm 1
  - python main_run.py --iterations 2 --replicas 2 --nrsteps 1000 --folderName 'test_travis' --algorithm 2
  - python main_run.py --iterations 2 --replicas 2 --nrsteps 1000 --folderName 'test_travis' --algorithm 3
  - python main_run.py --iterations 2 --replicas 2 --nrsteps 1000 --folderName 'test_travis' --algorithm 4
  - python main_run.py --iterations 2 --replicas 2 --nrsteps 1000 --folderName 'test_travis' --algorithm 4 --diffMapMetric 'rmsd'

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.5  CONDA_PY=35
    - python=3.6  CONDA_PY=36
#  global:
#    - OPENMM_CPU_THREADS="1" # only use one CPU thread for determinism

notifications:
  email: false
